### ISSUE TITLE
Please release to PyPi and tag on Github

### ISSUE THREAD

**Issue by paulfurley** [niwinz/djangorestframework-composed-permissions#8]
Hi, thanks for making this.

I've just installed from PyPi (version 0.1) which still has the typo of `Permisions` vs `Permission`. Can you please make a release to PyPi?

Also it would be super helpful if you could tag master at whatever point you release - otherwise it's very difficult to see what actual code is in the PyPi release.

Thanks,
Paul

**Comment by harrywhite4** [comment]
0.2 has been released and tagged

**Comment by paulfurley** [comment]
Much obliged!                                                                                                                                                                                                                                                                                                                From: notifications@github.comSent: 11 June 2018 7:22 amTo: djangorestframework-composed-permissions@noreply.github.comReply to: reply@reply.github.comCc: paul@paulfurley.com; author@noreply.github.comSubject: Re: [niwinz/djangorestframework-composed-permissions] Please release to PyPi and tag on Github (#8)
